### PR TITLE
added water.css for better styling & a Theme Switch !

### PR DESCRIPTION
**Pull request by 0xkarambit**
added [water.css](https://watercss.kognise.dev/) and the design looks much better without too much work !
it is now more responsive and more soothing to look at !
also added a theme switch button to toggle between light and dark themes !
theme switching is managed by simply changing theme attribute on :root element which changes the css variables in use.

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
Thanks! Would you mind posting a screenshot of how it looks with these changes?

**Comment by 0xkarambit** [comment]
ya sure ! Sorry how did i forget that :laughing: !

**Comment by 0xkarambit** [comment]
light1
light2
dark1
dark2

**Review by not-an-aardvark — APPROVED** [review]
Thanks!

**Pull request merged**
